#!/usr/bin/env bash

export MYAPP_WRAPPER="`readlink -f "$0"`"

HERE="`dirname "$MYAPP_WRAPPER"`"

if [[ -n "$LD_LIBRARY_PATH" ]]; then
	LD_LIBRARY_PATH="$HERE:$LD_LIBRARY_PATH"
else
	LD_LIBRARY_PATH="$HERE"
fi
export LD_LIBRARY_PATH

exec -a "$0" "$HERE/Popcorn-Time" "$@"
